language: go
sudo: required

go:
  - 1.8.x

services:
  - docker

env:
  global:
    - secure: "MMQON8M4wcIZMZf7o4d3CGQ/OgCEsaVa0rXlsKBl25wkQyF/+IWcvLoMK1AGp2YEy1BU32WtMEXAFgIBINBzzx23PTEf3MSxaZMPBdv44En1neuyL6FHGJT8af2r84sr0TRm9uZrGcXv4J5lXWgYh7N4nnOrtx7jIgWe/JiHGo6TlcnlplW1fSughdyu66OcSYJrlzqodSNhCOZ/rohTOJDnd7utfJXhgJ3MVZ60jbC55Ncy1PcU4QoJrlYe7CCvZhfijBBrYZL6ZBMbnDyL7oGcNMzNdwaBnYmqBIHS8Bf49o1T8SvOJLcEQhDSi9d4KODVbe0y0wF7xLkc+e8XRd3RURjJoLKUJwZIBHdAnhikFVzluSy4D+uJ+AUzkqqgvDS/UB7gzuCnTzq+oVluyxPJJT32HASW0qZOIajJDfC9J09Yp7y/RnXxmmwlFXMP9kqEUtW1zJD3K/sGqacgjxWrud/ZGbecMJiS/OqPiXF9/yZAQSNn4QQV7l+Pl0VGvX+VIVcO12gmWDaSanWO6emvu63TGsguVUsH71GabjOqalORsmMFTwT+a903KKdsfpaoBeMg2f0ORX9oERnxTEEEPFWGbYGdaALBx0C6KfUgLpB30QCXv2GwG7x4CAiQaM7hdHBl6f6uM0dR/bK/BZ001RPtQ386NpURe0LqsNs="
    - secure: "QC4VPpMAqt0mlkD+kVd3LXXSh2k6qze25Hf7+XqZbgKI/hHecsIUmOs0FYHCmGMfXAVPKi9p/iX+jpZPYEg1e5xje3tbkUty8wOOcmSwcqQhINyzZgv7+Qrn2CN2RplRow+EA4MSiaNxkH99c4miYKXaS8qpolcmja8u6sqRDt2X+dSF/8JE0IjTKgKf+6R8US3EYcklQ2bimMB6RrCn4Zgj4QQE7747pIa+tPmyRM4JGgWdxJfKrxoAp5idp7PWZ01vpxp/aQ1oXzJHIAdK1xPJ1qT+QdfF9FGStv3UhJKCBUR2YpxoUpwjiIScwBl2I9IsHMpyN5TV7oYAD2M3zkCeAxpYG5A27ko9tSWssKV6CCZjh77GmA7bCVuF+APWoWda7ilmVKVR/7njJU1gpBEkTFw5LOxd953tc8a5z+fOvCTbu8U1V/Gx6iXbJ+1zC32HmAnOwmreLu2MtgMccGDbYfcPC7mo7qcM7WWvlgjPlNcjb+qXHBUD5IuhJReOLVgknJYYqbqfHcIFHcvqITY5SQE9U35WoIbNqHD/q0FoaVGqgCF0j0fV5UoM5pO2+FhXzvrBslntKf5JBpFG1Wunob/XVlgDa3m4YkXWJJSOWe99/G+ZBPnTtmi2nHmzVm70ruhOdNFeQvUnJhEFfp4DsmyPF0OUyFsnAVZ9Tj0="

install:
  - make deps

script:
  - if [ -n "$TRAVIS_TAG" ]; then export VERSION="${TRAVIS_TAG//v/}"; fi
  - make dist

deploy:
  provider: script
  skip_cleanup: true
  script: make travis-release
  on:
    repo: servehub/serve-server
#    tags: true
