language: go
sudo: required

go:
  - 1.8.x

services:
  - docker

env:
  global:
    - secure: "MMQON8M4wcIZMZf7o4d3CGQ/OgCEsaVa0rXlsKBl25wkQyF/+IWcvLoMK1AGp2YEy1BU32WtMEXAFgIBINBzzx23PTEf3MSxaZMPBdv44En1neuyL6FHGJT8af2r84sr0TRm9uZrGcXv4J5lXWgYh7N4nnOrtx7jIgWe/JiHGo6TlcnlplW1fSughdyu66OcSYJrlzqodSNhCOZ/rohTOJDnd7utfJXhgJ3MVZ60jbC55Ncy1PcU4QoJrlYe7CCvZhfijBBrYZL6ZBMbnDyL7oGcNMzNdwaBnYmqBIHS8Bf49o1T8SvOJLcEQhDSi9d4KODVbe0y0wF7xLkc+e8XRd3RURjJoLKUJwZIBHdAnhikFVzluSy4D+uJ+AUzkqqgvDS/UB7gzuCnTzq+oVluyxPJJT32HASW0qZOIajJDfC9J09Yp7y/RnXxmmwlFXMP9kqEUtW1zJD3K/sGqacgjxWrud/ZGbecMJiS/OqPiXF9/yZAQSNn4QQV7l+Pl0VGvX+VIVcO12gmWDaSanWO6emvu63TGsguVUsH71GabjOqalORsmMFTwT+a903KKdsfpaoBeMg2f0ORX9oERnxTEEEPFWGbYGdaALBx0C6KfUgLpB30QCXv2GwG7x4CAiQaM7hdHBl6f6uM0dR/bK/BZ001RPtQ386NpURe0LqsNs="
    - secure: "0dC119ufBwmvrvzC+b1n5/BiutnY4hFxaRo/maSdKAfUX2b5UN438hTM5/ClkW9hN5dZS+FV8/gz05A7KL8lJ5hwamSU3zh4d2FYSawQXHssOamvxS2WPZaSCxm2qydcNhS7ArTLv9mbEeV01YXi2rhG7ud/HTzWVSz7Hab/lLzPsf+GdmqKcBc08TCg/6sjxV7Bnp0XF49bdxHmqtSYWxPhti9n/qs7IpZetkQo0L+xKngwq4OP0N7NADlgomiziolsG2Jb3DsQNdadkclWgNnl79JeVbj9LKdhhIEppTUGoWB8TT6BI58KEri41wAI6A+sFJWjcKD90HzpyPXruMz58PqBD2rOChVPgcGXAa1QQVrZ2O4TXat5Zwa+DGJCaia5di5HTScbfygNRLLwhiZsoUuw2Kc/hKCvSLCSBlwTZ1XDsWoG2AoihsZu7grnfZGyKxU/m6LzNyFmBmRgtlZjK1N8OuF0fXOcilMQq4i33KXXv42UnRBvlXwVQ/ra22rP/K92j/fivhoYfxGFcJMPNcW8EgQljG8MR5sZNyZaJS4j63CZhshOPnqvBwpGe7s/94LuPRhlBhRUJUfof3+zOJbnIyOvN0gOBL165B1I0sXYN7Uk5lHG8DjOymzxkAvf0RH/6TLSufanuy7hoWJR7PyJkN+SdEPU9Sv24eQ="

install:
  - make deps

script:
  - if [ -n "$TRAVIS_TAG" ]; then export VERSION="${TRAVIS_TAG//v/}"; fi
  - make dist

deploy:
  provider: script
  skip_cleanup: true
  script: >
    echo "$DOCKER_USERNAME" && \
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && \
    docker build -t servehub/serve-server:latest -t servehub/serve-server:${VERSION} . && \
    docker push servehub/serve-server:${VERSION} && \
    docker push servehub/serve-server:latest && \
    docker logout
  on:
    repo: servehub/serve-server
#    tags: true
