sudo: required
language: go

go:
  - 1.8.x

services:
  - docker

env:
  global:
    - secure: "MMQON8M4wcIZMZf7o4d3CGQ/OgCEsaVa0rXlsKBl25wkQyF/+IWcvLoMK1AGp2YEy1BU32WtMEXAFgIBINBzzx23PTEf3MSxaZMPBdv44En1neuyL6FHGJT8af2r84sr0TRm9uZrGcXv4J5lXWgYh7N4nnOrtx7jIgWe/JiHGo6TlcnlplW1fSughdyu66OcSYJrlzqodSNhCOZ/rohTOJDnd7utfJXhgJ3MVZ60jbC55Ncy1PcU4QoJrlYe7CCvZhfijBBrYZL6ZBMbnDyL7oGcNMzNdwaBnYmqBIHS8Bf49o1T8SvOJLcEQhDSi9d4KODVbe0y0wF7xLkc+e8XRd3RURjJoLKUJwZIBHdAnhikFVzluSy4D+uJ+AUzkqqgvDS/UB7gzuCnTzq+oVluyxPJJT32HASW0qZOIajJDfC9J09Yp7y/RnXxmmwlFXMP9kqEUtW1zJD3K/sGqacgjxWrud/ZGbecMJiS/OqPiXF9/yZAQSNn4QQV7l+Pl0VGvX+VIVcO12gmWDaSanWO6emvu63TGsguVUsH71GabjOqalORsmMFTwT+a903KKdsfpaoBeMg2f0ORX9oERnxTEEEPFWGbYGdaALBx0C6KfUgLpB30QCXv2GwG7x4CAiQaM7hdHBl6f6uM0dR/bK/BZ001RPtQ386NpURe0LqsNs="
    - secure: "n0BRaINEF3Ky7uuOGr/FIosoA2jCI+5IjDrMSKlIrJLs6NYtva6WwgUsXJjafRLYgHGThsEKdReEBZ4aHq3ths3rnpgdrrN0fj+HlwKg5UMQT+hzZ9vUqRfWaQbgirD1ngIsQDBI4Mo9e4H9KSwt4TQctgnxJbQo8+hIQW9tWeiJRIwemz1YY32wqxpBgGE4JivImoY07agVqQrg7+LF41+yA2da76+Dx6BeGjpC3BmX5jYXHodKmZhXh4ZaZiZPCllrvOmNkMETOxLJHR0mM2JeE59tnVZ0AWsbKtMN0NM6kqwSIzXzh2URcf0RS8VgvfZBCG7uHGvSf5Er4m1kiSj8nR9Ey8p+U+PTxCC1XsROXAcQ4PHRO1XZLLv9cUZfAngF/NaBUxx6+TxvuhhBz5Lwa9ljxs0lF1kyw0OBR3Qu5JQ43K6vD9zN732GIshEOXQhCFxzyjYTj3MItDdae/Ib4jsx6tQiDlzCLWJEQI0Ef2xqCZ0+TcUAEsusgtJYotrPUlSrYt11kXQHhcJAVzlX56tj0kLdjdJ1FUgoJM6Yrn+aQ5MWzMMVomFPLBFpcp/E1EmQmaROyZeuxmCDmmFZ/obmqOU48/1l7TYOEHfaMXji52OR/z23OE9FaHCW39eJdSyn37It4FXosp9g4cdVpM3MkMUL+lOQXoSxULE="

install:
  - make deps

script:
  - if [ -n "$TRAVIS_TAG" ]; then export VERSION="${TRAVIS_TAG//v/}"; fi
  - make dist
  - bin/serve-server --version
  - make travis-release

deploy:
  provider: releases
  api_key:
    secure: xlOI7+hAmEXTtFiyOPgE6M26+14urX9/fjtK5rv4SCEPgH0NUBEI9xDoXq+n4tBaBv1gUxQsW1X7qINmsCv1qmVvkxNIsZOXBppElm90Fk2PtnD+0GPCUxKufokDn7TkWJVIj8TzLVazvOTiFC9bkE2FIaNFz5ybfCDtQ7H8c2NpiaXnlqEm8lcgojtCBwPYMaGopRlwtJtiW+XLBzsd92xZji58xsuaIGa81wAlH63ZFUUrvfiDPHWnupOuE7tIxdLnbcAf16yLMRdVaCHPHg1TfbIq9ISQmA0/yNfWrErUBS6yMPTPERuBgAs/D8gxlEgQoltnWgMxrH8WR7lMrUhSkVuxDA5BI2CB6UG3xnh/hIDlBxQ3ScttaXoU88rsL6bZXv2XK4J5c+7WDq8SjtCVHPTBShymFVLn3gV9pH7IoWIbjQ3YW1yXKmjJecj7dp4Ddv+138dHvE4JuuoOls7ZyrBicM9z0m/qOzr0Q1YemPMwJIQzUl9ZaDssFDyd68x05K1B5i1aWVAiWzlM+OlIEVfjSdeZxEohiPY7O+ihoVadOyApIDOUi0ugJyg4hUU4JXbNhzLq0o3EnAysd4/UhfiGO+w0WUA3EAJG+k7qZ4Aain+DMMU1/0m6Ham+odX6W/5XiBBEoU9ip1bhiQjqq2zKoI/TwYUOnpH3IN4=
  file_glob: true
  file: bin/*
  overwrite: true
  skip_cleanup: true
  on:
    repo: servehub/serve-server
