logging:
  level: debug
  formatter: text

handlers:
  serve-undeploy-service: {}

  consul-remove-outdated:
    outdated-prefix: "services/outdated/"
    service-data-prefix: "services/data/"
    check-interval: 15s
    consul: 127.0.0.1:8500

  debug-handler:
    listen: ":8013"

  webhooks-server:
    listen: ":8088"
    secret-key: "sdf87adfkj234g"

  webhooks-bitbucket: {}

  webhooks-gitlab: {}

  webhooks-github:
    token: "XXX"

  webhooks-pingdom:
    slack-url: "https://hooks.slack.com/services/XXX/YYY/sdfsdf..."

  gocd-create-pipeline: {}

  create-dashboards:
    env: dev

  update-monitoring-alerts:
    env: dev
