logging:
  level: debug
  formatter: text

handlers:
  serve-commands:
    serve-path: serve
    consul: 127.0.0.1:8500
    service-data-prefix: "services/data/"

  consul-check-outdated:
    prefix: "services/outdated/"
    check-interval: 15s
    consul: 127.0.0.1:8500

  webhooks-server:
    listen: ":8088"
