logging:
  level: debug
  formatter: text

handlers:
  serve-undeploy-service:
    env: qa
    zone: qa

  consul-remove-outdated:
    outdated-prefix: "services/outdated/"
    service-data-prefix: "services/data/"
    check-interval: 15s
    consul: 127.0.0.1:8500
    cleanup-branches: false

  debug-handler:
    listen: ":8013"

  webhooks-server:
    listen: ":8088"
    secret-key: "sdf87adfkj234g"

  webhooks-bitbucket: {}

  webhooks-gitlab: {}

  webhooks-github:
    xhub-secret: ""
    token: "XXX"

  webhooks-pingdom:
    slack-url: "https://hooks.slack.com/services/XXX/YYY/sdfsdf..."

  gocd-create-pipeline: {}

  gocd-github-notify:
    notify-url: "http://go.mysite.com/go/api/webhooks/github/notify"

  gocd-run-pipeline:
    gocd-url: "https://go.mysite.com"
    gocd-env: "default"

    pipelines:
      - repo: git@github.com:test/test.git
        pipeline: my-pipeline-name

  create-dashboards:
    env: dev

  update-monitoring-alerts:
    env: dev
    zone: dev
